apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubectl-cronjob
spec:
  schedule: 46 07 10 12 *
  jobTemplate:
    spec:
      template:
        spec:
          #initContainers:
          #- name: git-repo
          #  args: ["apk add git && git clone https://${PAT}@github.com/${OWNER}/${REPO} /repo && cd /repo && git fetch origin pull/$PR_NUM/head:tmp"]
          containers:
          - name: kubectl
            args:
            - get
            - po
