apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- envs:
  - secret.env
  name: kubectl-cronjob
resources:
- cronjob.yaml
