name: Kustomize

on:
  pull_request:
    paths:
    - base/**
    - overlay/**
    - aqua.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mikutas/my-aqua-installer@v0.2.1

      - run: |
          echo PAT=${{ secrets.GITHUB_TOKEN }} > base/secret.env
          echo OWNER=mikutas >> base/secret.env
          echo REPO=helm-charts-for-app-of-apps-experiment

      - run: kustomize build overlay
